# Generated by Django 5.1.1 on 2024-09-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('M', 'M.'), ('F', 'Mme')], default='M', max_length=1),
        ),
    ]
